### ISSUE TITLE
Which hardware is being used for this pcb?

### ISSUE THREAD

**Issue by ZhengLinLei** [shawnalexsony/Business_Card_PCB#2]

**Comment by ZhengLinLei** [comment]
I searched all NT3H1101 components, but any with 9 pads

**Comment by shawnalexsony** [comment]
Hi,

I have used the part : **NT3H1101W0FHKH** from NXP semiconductors.
I ordered from JLC PCB. Please check with them.

Also, it seems some of the production build has 9 pads IC, but 9th pad is an NC pin. Datasheet shows only 8 pins, so you can use the 8 pin version since footprint also has 8 pads only.

**Comment by ZhengLinLei** [comment]
Ok, thanks!
